### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by michalsustr** [googlecreativelab/quickdraw-dataset#1]
Hello, are you also considering releasing the trained neural network used for recognition of images? O:-) The Sketch-RNN is a generative model, from what I understand by a quick look.

**Comment by kylemcdonald** [comment]
Sketch-RNN pretrained models are linked to on the Magenta repo: https://github.com/tensorflow/magenta/tree/master/magenta/models/sketch_rnn#pre-trained-models
