### ISSUE TITLE
It doesnt recognise a penis

### ISSUE THREAD

**Issue by EzraOW** [googlecreativelab/quickdraw-dataset#10]

**Comment by doodlewoman** [comment]
It might be just having some issues recognizing yours.

**Comment by sterlingcrispin** [comment]
@EzraOW this is bad and you should feel bad

**Comment by makc** [comment]
I think it's because it mistakes it for the shoe:


![screen shot 2017-06-24 at 2 54 21](https://user-images.githubusercontent.com/242577/27504378-b595d254-5888-11e7-9ad1-139567e966f4.png)

**Comment by HalfdanJ** [comment]
Intended behavior
