### ISSUE TITLE
One-to-one correspondence between datasets in different formats

### ISSUE THREAD

**Issue by xinpl** [googlecreativelab/quickdraw-dataset#13]
Hi,

Thanks for sharing this awesome dataset. I want to use both the bitmap dataset and the meta information contained in the original raw dataset. So I am wondering if there is a one-to-one correspondence between entries with the same indices in these two datasets?

Thanks.

**Comment by HalfdanJ** [comment]
Sorry for slow reply on this. I'm pretty sure they should match. Did you have a good at it yourself?

**Comment by xinpl** [comment]
Yes. I sampled some points and they matched.
