### ISSUE TITLE
Script for rendering simplified images to 28x28 grayscale numpy format

### ISSUE THREAD

**Issue by lambdabaa** [googlecreativelab/quickdraw-dataset#27]
Can the script that was used to convert from `.ndjson` to `.npy` be open-sourced? I've trained a model on the `.npy` files and want to be able to take new `.ndjson` examples and run them through my model. Thanks!

**Comment by hlxabcd** [comment]
I had the same problem. Is it possible to open source`. ndjson` to`. npy` code? Thanks a lot！

**Comment by HalfdanJ** [comment]
Hi, 

I dont have code that converts from ndjson to npy directly, but here is some code that generates the npy data from an array. This is the code that has been used to generate the dataset

https://github.com/googlecreativelab/quickdraw-dataset/issues/19#issuecomment-402247262

**Comment by hlxabcd** [comment]
Thank you very much for your help. It really helped me a lot！

**Comment by talhakabakus** [comment]
Hi @HalfdanJ ,
Thanks for this amazing dataset which is really useful for my academic researches related deep learning. I just need to convert the original image data (which has a purple background with yellow strokes) to the one presented in the https://quickdraw.withgoogle.com/data. In short, I need to convert this image to the one below:
![dog_2](https://user-images.githubusercontent.com/444482/57184796-862ba580-6ec9-11e9-9702-89b3367cc979.png)

![dog](https://user-images.githubusercontent.com/444482/57184811-c7bc5080-6ec9-11e9-92f6-5c1a032376a5.png)

Here is how I load the one sample image stored in a `.npy` file and display it using `matplotlib.pyplot`:

```
def main():
    category = 'zebra'
    npy_file_path = DATASET_PATH + category + '.npy'
    data = np.load(npy_file_path)

    for sample in data:
        sample = sample.reshape((28, 28))
        plt.imshow(sample)
        plt.show()
        break
```

Could you please guide me through the conversion process?
