### ISSUE TITLE
How to transform .npz to photograph

### ISSUE THREAD

**Issue by Hansxsourse** [googlecreativelab/quickdraw-dataset#30]
Hi
Now our team want to use the .npz dataset to do other research,but we tried many times, we can't transform the .npz numpy array to the grtaph like .jpg or .png. we show the shape about the array is (28,3). so we can't get back to rgb graph.
We read the quick draw rnn dataset paper, still don't know how to transform them.
Can you help me to solve it out?

Best wishes
Hans Yang

**Comment by muskanvk** [comment]
given a numpy array "A":

from PIL import Image
im = Image.fromarray(A)
im.save("your_file.jpeg")

you can replace "jpeg" with almost any format you want.
Hope this helps

**Comment by Hansxsourse** [comment]
> given a numpy array "A":
> 
> ```
> from PIL import Image
> im = Image.fromarray(A)
> im.save("your_file.jpeg")
> ```
> 
> you can replace "jpeg" with almost any format you want.
> Also try this out using scipy
> `from scipy.misc import toimage toimage(data).show()`
> 
> Hope this helps

Cheers!
Thabks for reply!

**Comment by bryanbocao** [comment]
@Hansxsourse Have you solved that? I got the data shape like ```np.shape(data):  (124612, 784))``` but could not find the details of this format. It's not in the shape of an image 28x28. I know 28x28=784 but what are the specific values in this 784-dim vector mean? Do they follow the format of ```[x0, x1, x2, ... y0, y1, y2, ...]``` or ```[x0, y0, x1, y1, x2, y2, ...]```? Thanks!
