### ISSUE TITLE
Time until first point?

### ISSUE THREAD

**Issue by annafergusson** [googlecreativelab/quickdraw-dataset#36]
At the moment, the first point of the first stroke has t = 0. It would be super interesting to also be able to know how many milliseconds after the player was asked to draw something they actually made their first stroke! Is there anyway of incorporating this info in any future releases of the data set?

**Comment by HalfdanJ** [comment]
I agree that this would sometimes be an interesting datapoint to have. Unfortunately it is not data we have collected, so its not feasible to add to the dataset.
