### ISSUE TITLE
How are authors' rights handled?

### ISSUE THREAD

**Issue by lehni** [googlecreativelab/quickdraw-dataset#4]
Wouldn't Quick, Draw! either need to make it clear to its users that their drawings were going to be open sourced, or get permission for all 50 million users before open-sourcing their hand-made drawings?

I am curious about the implications of Authors' Rights in such projects. No matter how small and simple a drawing, it is still a unique, hand created artefact and therefore such rights surely apply?

How is this handled by Google?

**Comment by 0Bee** [comment]
In the main page you will see the message big and prominent "shared **publicly** to help with machine learning research."   ¯\_(ツ)_/¯

![google quick draw](https://cloud.githubusercontent.com/assets/26209038/26331510/9f987e78-3f94-11e7-94dc-ddead6e8b087.PNG)

**Comment by lehni** [comment]
Oops my bad. I was looking for this information, but got the projects mixed up and looked on https://www.autodraw.com/ instead. Just ignore this then : )
