### ISSUE TITLE
How could I get information like "countrycode" in numpy_bitmap dataset.

### ISSUE THREAD

**Issue by XiaoyunQIN** [googlecreativelab/quickdraw-dataset#40]
Hello,

I wonder how could I get information like "word", "countrycode", "recognized" in numpy_bitmap. I use up.load() to get the data and the only information I got is about the image. I wonder how could I get more information.

I tried binary data. It contains the information data I need but I want the image into 28*28 format. I tried to use vector_to_raster() function but failed since my image format is like:

[((0, 31, 70, 97, 121, 195, 230), (46, 38, 9, 0, 0, 29, 32)),
 ((3, 24, 98, 118, 157, 181, 197, 212, 255),
  (46, 45, 72, 83, 88, 77, 54, 42, 30)),
 ((120, 109, 99, 92, 91, 105, 116, 129, 142, 150, 155, 156, 146, 109),
  (1, 2, 11, 25, 41, 66, 75, 79, 77, 66, 54, 28, 15, 1)),
 ((109, 104, 103, 113, 122, 138, 146, 150), (8, 13, 32, 51, 57, 57, 52, 44))]

Thank you so much for your help! :)

**Comment by HalfdanJ** [comment]
I think you will have to use the binary files to do this. 

Whats the error you are having with the `vector_to_raster` function? It should accept exactly that vector format coming out of the binary file

**Comment by XiaoyunQIN** [comment]
Hi HalfdanJ,

The error I got is: 
![image](https://user-images.githubusercontent.com/46976113/69160990-70be4780-0ab8-11ea-9ce3-ebe3a95ff79f.png)
Thank you so much for your help!

**Comment by HalfdanJ** [comment]
Try doing `vector_to_raster([image])` instead. The function takes an array of images. A little unclear, sorry!

**Comment by XiaoyunQIN** [comment]
It works！！ Thank you so much for your help!!!!

**Comment by HalfdanJ** [comment]
Glad to hear
