### ISSUE TITLE
Error with Placeholder_1

### ISSUE THREAD

**Issue by Pauladds** [googlecreativelab/quickdraw-dataset#41]
I tried to run el script https://github.com/tensorflow/magenta-demos/blob/master/jupyter-notebooks/Sketch_RNN.ipynb but with diferente dataset (bread.npz) and with the checkpoints of that and i have the next problem :
![69332857-d8f75f80-0c57-11ea-813c-22fe4db6b636]
(https://user-images.githubusercontent.com/38189240/69523732-e2890c00-0f64-11ea-9e81-62b97e725735.png)

Here is the code (https://github.com/Pauladds/Rnn_sketch) , i am running "blob_sketch_RNN-bread" but i don't know my problem...

**Comment by HalfdanJ** [comment]
This is probably an issue that is better to post on https://github.com/tensorflow/magenta-demos.
