### ISSUE TITLE
Modern numpy.load does not accept these .npz files

### ISSUE THREAD

**Issue by LanceNorskog** [googlecreativelab/quickdraw-dataset#45]
What is a current, up-to-date code sample that can load the .npz files in this distribution?
This no longer works in Python 3:

import numpy as np
x = np.load(file_path, allow_pickle=True, encoding='latin1')
print(x.keys())

Here is the error for 'cats.npz'

>>> x = np.load(file, allow_pickle=True)
Traceback (most recent call last):
  File "/Users/l0n008k/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 454, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, '\x0a'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/l0n008k/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 457, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file '/Users/l0n008k/Downloads/cat.npz' as a pickle

**Comment by Sunstar007-lab** [comment]
please stop sending this to me
"LIfe doesn't give you seatbelts"

**Comment by LanceNorskog** [comment]
I downloaded a similar file of sheep from the 'Aaron Sheep' collection, and that .npz worked. It looks like the numpy library people have somehow dropped compatibility with some old files.

Where would I find the code for turning the .ndjson files into .npz files? Is that available?

The context is that I would like to do something similar with vector-based emoji files, and the sketch-rnn technology base is really attractive.

Thanks,

Lance Norskog

p.s. I released the 'sox' sound file manipulation CLI tool in 1990, and so am quite familiar with receiving emails about old projects in which I have lost interest. Vaya con dios!

**Comment by hardmaru** [comment]
Hi there, I may have an old notebook somewhere to convert .ndjson into .npz

I also found that converting the raw nd json's (rather than the simplified ones) using a finer RDP parameter results in better quality sketch-rnn models, so you may want to do it anyways

Let me go look for it later this weekend!

**Comment by hardmaru** [comment]
Hi @LanceNorskog 

The instructions in README.md has been updated now for loading the old `npz` files in Python3 (https://github.com/googlecreativelab/quickdraw-dataset)

Also, as you were looking for code for turning the .ndjson files into .npz files, I've also put a link to a notebook from the readme as well (in the sketch-rnn section).

Good luck with the vector-based emoji!

**Comment by HalfdanJ** [comment]
Closing this issue as it seems hardmarus comment should be solving it.
