### ISSUE TITLE
Is there a way to view drawings by subject?

### ISSUE THREAD

**Issue by sunk818** [googlecreativelab/quickdraw-dataset#5]
So, there are 345 categories. I'm curious how the drawings look by each category. I'd like a way to just see airplanes on one screen.

**Comment by HalfdanJ** [comment]
Line this you mean? 
https://quickdraw.withgoogle.com/data/airplane

**Comment by sunk818** [comment]
Yes, exactly. How did you do that? ;) I guess I didn't navigate or read carefully?

**Comment by geordielad** [comment]
If you start at https://quickdraw.withgoogle.com/data then click on any drawing (all 345 are there in the grid 15*23) you go to a page with every example of that name.
