### ISSUE TITLE
Any way to export the image as .png/.jpg from the ndjson/bin file.

### ISSUE THREAD

**Issue by neelkadia** [googlecreativelab/quickdraw-dataset#6]
I'm not getting how the block describe the image. Is there any way I can export _image_ as png/jpg?
example block:
``{
	'key_id': 6545061917491200,
	'image': [((54, 37, 7, 5, 12, 0, 7, 34, 52, 56, 52, 42, 38), (66, 49, 8, 11, 63, 105, 105, 89, 84, 88, 149, 205, 255)), ((59, 62, 88, 95, 97), (66, 13, 1, 1, 33))],
	'recognized': 1,
	'countrycode': 'SE',
	'timestamp': 1485553794
}``

**Comment by HalfdanJ** [comment]
We haven't created any example codes to export png/jpg images at the moment, so currently you would need to create that yourself, or look at some of the SVG export links in #3. 

The `image` block in the ndjson file is arrays of `x`and `y` coordinates (and `t` - time, if its the raw format), separated by different strokes. So the first array you see are `x` coordinates, and the second is `y` coordinates.

**Comment by C-Aniruddh** [comment]
@neelkadia @HalfdanJ I did create a script to convert .npy bitmaps to 28x28 jpg files for a simple project!

Find it here : https://github.com/C-Aniruddh/RapidDraw/blob/in-dev/processing/process_all.py 

Cheers 🍺

**Comment by Wendelin-Roth** [comment]
Hey @C-Aniruddh!
Is your script still available? Because the link you posted here isn't working anymore...
