### ISSUE TITLE
Link to tensorflow does not work

### ISSUE THREAD

**Issue by John-Val** [googlecreativelab/quickdraw-dataset#66]
This link does not work any longer.
https://www.tensorflow.org/tutorials/sequences/recurrent_quickdraw

**Comment by HalfdanJ** [comment]
Good catch. Seems like its still available here: https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/recurrent_quickdraw.md

**Comment by John-Val** [comment]
Thank you very much!

Op 23 mrt. 2021 3:22 p.m. schreef Jonas Jongejan ***@***.***>:

Good catch. Seems like its still available here: https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/recurrent_quickdraw.md
