### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by thevishnupradeep** [googlecreativelab/quickdraw-dataset#73]
It looks like all data links in readme are broken. Thank you for this amazing work. It would be great this issue could be fixed. thank you.

**Comment by adenek** [comment]
+1 here, could you please update the links in the "Full dataset seperated by categories", they are all broken

**Comment by HalfdanJ** [comment]
LInks have been updated now. Google cloud had changed their urls, so theres now an additional /browse in the url. Let me know if there are any other broken links to the dataset.
